# Generated by Django 4.0.2 on 2022-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transfer_reciver_username_alter_accountdetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='account_ready',
            field=models.BooleanField(default=False),
        ),
    ]
